# -*- coding: utf-8 -*-
"""
/***************************************************************************
 tky2jgd
                                 A QGIS plugin
 日本測地系に基づく経緯度を世界測地系に基づく経緯度へ変換する
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-06-29
        git sha              : $Format:%H$
        copyright            : (C) 2019 by ozaki
        email                : ozaki360@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.core import *

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .tky2jgd_dialog import tky2jgdDialog
import os.path

class tky2jgd:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'tky2jgd_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&tky2jgd')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('tky2jgd', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """
        # Create the dialog (after translation) and keep reference
        self.dlg = tky2jgdDialog(self.iface.mainWindow())

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/test_plugin/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'TKY2JGD'),
            callback=self.run,
            parent=self.iface.mainWindow())

        self.dlg.btn1.clicked.connect(self.buttonClicked)


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&tky2jgd'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    ###################################
    # 処理開始ボタンクリック
    ###################################
    def buttonClicked(self):
        self.layer = self.iface.activeLayer()
        if not self.isScope():
            return

        self.wkbType = QgsWkbTypes.displayString(self.layer.wkbType())

        # 座標変換パラメータ辞書を生成
        self.loadPar()
        # 座標変換クラスを生成
        self.setCrsTrans()

        # 変換処理
        self.execTrans()
        QMessageBox.information(self.dlg, 'tky2jgd', 'finished')
        
    ###################################
    # 変換パラメータファイルを読み込み
    ###################################
    def loadPar(self):
        self.par = {}
        parfile = 'TKY2JGD.par'
        with open(os.path.join(os.path.abspath(os.path.dirname(__file__)), parfile)) as f:
            # ヘッダの2行飛ばす
            skip = 2
            for i in range(skip):
                next(f)

            # 1行づつ読み込んでdistに格納
            while True:
                line = f.readline()
                if not line:
                    # EOF
                    break
                # 値は秒なのでここで割っておく
                self.par[int(line[0:8])] = (float(line[8:18]) / 3600, float(line[18:28]) / 3600)

    ###################################
    # 変換対象レイヤかどうかを判定
    # （ついでに変換前後のsridと緯度経度フラグを保持する）
    ###################################
    def isScope(self):
        try:
            if not isinstance(self.layer, QgsVectorLayer):
                raise ValueError("activeLayer is not QgsVectorLayer")

            self.srid = self.layer.crs().postgisSrid()
            if self.srid == 4301:
                self.isLonlat = True
                self.toSrid = 4612
            elif (self.srid > 30160 and self.srid < 30180):
                self.isLonlat = False
                self.toSrid = 2442 + self.srid - 30160
            else:
                # 対象外のSRID
                raise ValueError("activeLayer is not Tokyo Datum")

            wkbType = self.layer.wkbType()
            # point line polygonを対象とする
            if not QgsWkbTypes.geometryType(wkbType) in [
                    QgsWkbTypes.PointGeometry, 
                    QgsWkbTypes.LineGeometry, 
                    QgsWkbTypes.PolygonGeometry]:
                # 対象外のgeometryType
                raise ValueError("activeLayer is out of scope geometryType")

            # 2次元レイヤを対象とする
            if QgsWkbTypes.hasZ(wkbType) or QgsWkbTypes.hasM(wkbType):
                # 対象外のwkbType
                raise ValueError("activeLayer is out of scope wkbType")

        except ValueError as e:
            # 対象外
            self.iface.messageBar().pushMessage("tky2jgd <b>{}</b>".format(e), Qgis.Warning)
            return False
        else:
            # 対象
            return True

    ###################################
    # 座標変換処理
    ###################################
    def execTrans(self):
        # 変換後レイヤを生成
        afterLayer = self.createAfterLayer()

        # 編集開始
        afterLayer.startEditing()
        fields = afterLayer.fields()

        inFeat = QgsFeature()
        feats = self.layer.getFeatures()
        while feats.nextFeature( inFeat ):
            attributes = inFeat.attributes()
            beforeGeom = QgsGeometry( inFeat.geometry() )
            if not self.isLonlat:
                beforeGeom.transform(self.trans4301)
            afterGeom = self.moveCorrection(beforeGeom)
            afterGeom.transform(self.transTo)

            feature = QgsFeature(fields)
            feature.setAttributes(attributes)
            feature.setGeometry(afterGeom)
            
            afterLayer.addFeature(feature)

        # 編集終了
        afterLayer.commitChanges()
        QgsProject.instance().addMapLayer(afterLayer)

    ###################################
    # 変換後のメモリレイヤを作成
    ###################################
    def createAfterLayer(self):
        layerUri = self.wkbType +"?crs=postgis:" + str(self.toSrid)
        afterLayer = QgsVectorLayer(layerUri, "exchange", "memory")
        afterLayer.dataProvider().addAttributes(self.layer.fields())
        return afterLayer

    ###################################
    # 地物の頂点移動
    ###################################
    def moveCorrection(self, geom):
        for i, v in enumerate(geom.vertices()):
            meshcode = self.Coordinate2MeshCode(v.y(), v.x())
            correction = self.par[meshcode]
            geom.moveVertex(v.x() + correction[1], v.y() + correction[0], i)
        return geom
    
    ###################################
    # 座標変換クラスを生成
    ###################################
    def setCrsTrans(self):
        crs4301 = QgsCoordinateReferenceSystem(4301, QgsCoordinateReferenceSystem.EpsgCrsId)
        if not self.isLonlat:
            crsFrom = QgsCoordinateReferenceSystem(self.srid, QgsCoordinateReferenceSystem.EpsgCrsId)
            self.trans4301 = QgsCoordinateTransform(crsFrom, crs4301, QgsProject.instance())

        crsTo = QgsCoordinateReferenceSystem(self.toSrid, QgsCoordinateReferenceSystem.EpsgCrsId)
        self.transTo = QgsCoordinateTransform(crs4301, crsTo, QgsProject.instance())

    ###################################
    # メッシュコード算出
    # 
    # Create by @mormor
    # https://qiita.com/mormor/items/3643847653e21007f29d
    ###################################
    def Coordinate2MeshCode(self, dLat, dLng ):
        # cf: http://white-bear.info/archives/1400
        # Make sure the input values are decimal 
        iMeshCode_1stMesh_Part_p = dLat *60 // 40
        iMeshCode_1stMesh_Part_u = ( dLng - 100 ) // 1
        iMeshCode_2ndMesh_Part_q = dLat *60 % 40 // 5
        iMeshCode_2ndMesh_Part_v = ( ( dLng - 100 ) % 1 ) * 60 // 7.5
        iMeshCode_3rdMesh_Part_r = dLat *60 % 40 % 5 * 60 // 30
        iMeshCode_3rdMesh_Part_w = ( ( dLng - 100 ) % 1 ) * 60 % 7.5 * 60 // 45
        iMeshCode = iMeshCode_1stMesh_Part_p * 1000000 + iMeshCode_1stMesh_Part_u * 10000 + iMeshCode_2ndMesh_Part_q * 1000 + iMeshCode_2ndMesh_Part_v * 100 + iMeshCode_3rdMesh_Part_r * 10 + iMeshCode_3rdMesh_Part_w
        return iMeshCode
